package vistaGestionUsuario;
import Vista.vistaPanelPrincipal;

/* Panel correspondiente al modulo de configuracion de usuario en la aplicación */
public class panelConfiguracion extends javax.swing.JPanel {

    public panelConfiguracion() {
        initComponents();
        this.setLocation(0, 100);
    }

    public vistaPanelPrincipal vistapanelprincipal;

    public void setvistaGestionUsuarios(vistaPanelPrincipal vistapanelprincipal) {
        this.vistapanelprincipal = vistapanelprincipal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     *
     *
     */
    /**
     * This method is called from within the constructor to initialize the
     * form.WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     *
     * @param evt
     */
    public void soloNumeros(java.awt.event.KeyEvent evt) {
        char car = evt.getKeyChar();
        if (jtxTelefono.getText().length() >= 20 || jtxIdentificacion.getText().length() >= 20) {
            evt.consume();
        }
        if ((car < '0' || car > '9')) {
            evt.consume();
        }
    }

    public void soloLetras(java.awt.event.KeyEvent evt) {

        char car = evt.getKeyChar();
        System.out.println((int) car);
        if (jtxNombres.getText().length() >= 20 || jtxApellidos.getText().length() >= 20) {
            evt.consume();
        }
        if ((((int) car >= 65 && (int) car <= 90)) || (((int) car >= 97 && (int) car <= 122))) {

        } else {
            evt.consume();
        }

    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnFondo = new javax.swing.JPanel();
        jlbNombres = new javax.swing.JLabel();
        jlbApellidos = new javax.swing.JLabel();
        jtxApellidos = new javax.swing.JTextField();
        jlbIdentificacion = new javax.swing.JLabel();
        jlbCorreo = new javax.swing.JLabel();
        jtxNombres = new javax.swing.JTextField();
        jtxTelefono = new javax.swing.JTextField();
        jtxtCorreo = new javax.swing.JTextField();
        jlbTipoDoc = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jlbDependencia = new javax.swing.JLabel();
        jlbTelefono = new javax.swing.JLabel();
        cmbTipoDoc = new javax.swing.JComboBox<>();
        jlbMsjAdvertencia = new javax.swing.JLabel();
        jtxDependencia = new javax.swing.JTextField();
        jtxIdentificacion = new javax.swing.JTextField();
        jpnSeguridad = new javax.swing.JPanel();
        jlbContrasena1 = new javax.swing.JLabel();
        jpasContrasena = new javax.swing.JPasswordField();
        jlbContrasena2 = new javax.swing.JLabel();
        jpasContrasena2 = new javax.swing.JPasswordField();
        jpnPersonal = new javax.swing.JPanel();
        jlbTitulo = new javax.swing.JLabel();

        jpnFondo.setBackground(new java.awt.Color(255, 255, 255));
        jpnFondo.setEnabled(false);
        jpnFondo.setPreferredSize(new java.awt.Dimension(5000, 1550));
        jpnFondo.setRequestFocusEnabled(false);
        jpnFondo.setVerifyInputWhenFocusTarget(false);
        jpnFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbNombres.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jlbNombres.setForeground(new java.awt.Color(51, 51, 51));
        jlbNombres.setText("Nombres");
        jpnFondo.add(jlbNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 80, -1));

        jlbApellidos.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jlbApellidos.setForeground(new java.awt.Color(51, 51, 51));
        jlbApellidos.setText("Apellidos ");
        jpnFondo.add(jlbApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, -1, -1));

        jtxApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxApellidosKeyTyped(evt);
            }
        });
        jpnFondo.add(jtxApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 270, -1));

        jlbIdentificacion.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jlbIdentificacion.setForeground(new java.awt.Color(51, 51, 51));
        jlbIdentificacion.setText("Identificación ");
        jpnFondo.add(jlbIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 120, -1));

        jlbCorreo.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jlbCorreo.setForeground(new java.awt.Color(51, 51, 51));
        jlbCorreo.setText("Correo");
        jpnFondo.add(jlbCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 100, -1));

        jtxNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxNombresKeyTyped(evt);
            }
        });
        jpnFondo.add(jtxNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 270, -1));

        jtxTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxTelefonoKeyTyped(evt);
            }
        });
        jpnFondo.add(jtxTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 270, -1));
        jpnFondo.add(jtxtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 270, -1));

        jlbTipoDoc.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jlbTipoDoc.setForeground(new java.awt.Color(51, 51, 51));
        jlbTipoDoc.setText("Tipo documento");
        jpnFondo.add(jlbTipoDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, -1));

        btnActualizar.setBackground(new java.awt.Color(153, 0, 0));
        btnActualizar.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar");
        jpnFondo.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 500, -1, -1));

        btnLimpiar.setBackground(new java.awt.Color(153, 0, 0));
        btnLimpiar.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("Limpiar");
        jpnFondo.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 500, 90, -1));

        jlbDependencia.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jlbDependencia.setForeground(new java.awt.Color(51, 51, 51));
        jlbDependencia.setText("Dependencia");
        jpnFondo.add(jlbDependencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 110, -1));

        jlbTelefono.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jlbTelefono.setForeground(new java.awt.Color(51, 51, 51));
        jlbTelefono.setText("Telefono         ");
        jpnFondo.add(jlbTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, -1, -1));

        cmbTipoDoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TI", "CE", "CC" }));
        jpnFondo.add(cmbTipoDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 270, 20));

        jlbMsjAdvertencia.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jlbMsjAdvertencia.setForeground(new java.awt.Color(51, 51, 51));
        jlbMsjAdvertencia.setText("jLabel1");
        jpnFondo.add(jlbMsjAdvertencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 540, -1));

        jtxDependencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxDependenciaKeyTyped(evt);
            }
        });
        jpnFondo.add(jtxDependencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 270, -1));

        jtxIdentificacion.setEditable(false);
        jtxIdentificacion.setBackground(new java.awt.Color(255, 255, 255));
        jtxIdentificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxIdentificacionKeyTyped(evt);
            }
        });
        jpnFondo.add(jtxIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 270, -1));

        jpnSeguridad.setBackground(new java.awt.Color(255, 255, 255));
        jpnSeguridad.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Seguridad", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 11), new java.awt.Color(51, 51, 51))); // NOI18N

        jlbContrasena1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jlbContrasena1.setForeground(new java.awt.Color(51, 51, 51));
        jlbContrasena1.setText("Contraseña nueva ");

        jpasContrasena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpasContrasenaMouseClicked(evt);
            }
        });
        jpasContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpasContrasenaActionPerformed(evt);
            }
        });

        jlbContrasena2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jlbContrasena2.setForeground(new java.awt.Color(51, 51, 51));
        jlbContrasena2.setText("Confirmación");

        jpasContrasena2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpasContrasena2MouseClicked(evt);
            }
        });
        jpasContrasena2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpasContrasena2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnSeguridadLayout = new javax.swing.GroupLayout(jpnSeguridad);
        jpnSeguridad.setLayout(jpnSeguridadLayout);
        jpnSeguridadLayout.setHorizontalGroup(
            jpnSeguridadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnSeguridadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnSeguridadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnSeguridadLayout.createSequentialGroup()
                        .addComponent(jlbContrasena1)
                        .addGap(37, 37, 37)
                        .addComponent(jpasContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnSeguridadLayout.createSequentialGroup()
                        .addComponent(jlbContrasena2)
                        .addGap(73, 73, 73)
                        .addComponent(jpasContrasena2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jpnSeguridadLayout.setVerticalGroup(
            jpnSeguridadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnSeguridadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnSeguridadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbContrasena1)
                    .addComponent(jpasContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jpnSeguridadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbContrasena2)
                    .addComponent(jpasContrasena2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jpnFondo.add(jpnSeguridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 100, 330, 110));

        jpnPersonal.setBackground(new java.awt.Color(255, 255, 255));
        jpnPersonal.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Información personal", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 11))); // NOI18N

        javax.swing.GroupLayout jpnPersonalLayout = new javax.swing.GroupLayout(jpnPersonal);
        jpnPersonal.setLayout(jpnPersonalLayout);
        jpnPersonalLayout.setHorizontalGroup(
            jpnPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );
        jpnPersonalLayout.setVerticalGroup(
            jpnPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 316, Short.MAX_VALUE)
        );

        jpnFondo.add(jpnPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 510, 340));

        jlbTitulo.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jlbTitulo.setText("Configuración de Usuario");
        jpnFondo.add(jlbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jpnFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 1400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jpnFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtxApellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxApellidosKeyTyped
        soloLetras(evt);  // TODO add your handling code here:
    }//GEN-LAST:event_jtxApellidosKeyTyped

    private void jtxNombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxNombresKeyTyped
        soloLetras(evt);
    }//GEN-LAST:event_jtxNombresKeyTyped

    private void jtxTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxTelefonoKeyTyped
        soloNumeros(evt);
    }//GEN-LAST:event_jtxTelefonoKeyTyped

    private void jpasContrasenaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpasContrasenaMouseClicked

    }//GEN-LAST:event_jpasContrasenaMouseClicked

    private void jpasContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpasContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpasContrasenaActionPerformed

    private void jpasContrasena2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpasContrasena2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jpasContrasena2MouseClicked

    private void jpasContrasena2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpasContrasena2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpasContrasena2ActionPerformed

    private void jtxDependenciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxDependenciaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxDependenciaKeyTyped

    private void jtxIdentificacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxIdentificacionKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxIdentificacionKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActualizar;
    public javax.swing.JButton btnLimpiar;
    public javax.swing.JComboBox<String> cmbTipoDoc;
    private javax.swing.JLabel jlbApellidos;
    public javax.swing.JLabel jlbContrasena1;
    public javax.swing.JLabel jlbContrasena2;
    private javax.swing.JLabel jlbCorreo;
    private javax.swing.JLabel jlbDependencia;
    public javax.swing.JLabel jlbIdentificacion;
    public javax.swing.JLabel jlbMsjAdvertencia;
    private javax.swing.JLabel jlbNombres;
    private javax.swing.JLabel jlbTelefono;
    public javax.swing.JLabel jlbTipoDoc;
    private javax.swing.JLabel jlbTitulo;
    public javax.swing.JPasswordField jpasContrasena;
    public javax.swing.JPasswordField jpasContrasena2;
    private javax.swing.JPanel jpnFondo;
    private javax.swing.JPanel jpnPersonal;
    private javax.swing.JPanel jpnSeguridad;
    public javax.swing.JTextField jtxApellidos;
    public javax.swing.JTextField jtxDependencia;
    public javax.swing.JTextField jtxIdentificacion;
    public javax.swing.JTextField jtxNombres;
    public javax.swing.JTextField jtxTelefono;
    public javax.swing.JTextField jtxtCorreo;
    // End of variables declaration//GEN-END:variables
}
