
package vistaGestionUsuario;

public class panelUsuario extends javax.swing.JPanel {

    public panelUsuario() {
        initComponents();
        jlbContrasena1.setVisible(false);
        jlbContrasena2.setVisible(false);
        jpsContrasena2.setVisible(false);
        jpsContrasena.setVisible(false);
    }
    
     public void soloNumeros(java.awt.event.KeyEvent KyEvt) {
        char ChCar = KyEvt.getKeyChar();
        if (jtxIdentificacion.getText().length() >= 20) {
            KyEvt.consume();
        }
        if ((ChCar < '0' || ChCar > '9')) {
            KyEvt.consume();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnFondo = new javax.swing.JPanel();
        jlbRol = new javax.swing.JLabel();
        jlbEstado = new javax.swing.JLabel();
        jlbModificarUsuario = new javax.swing.JLabel();
        jlbUsuario = new javax.swing.JLabel();
        jtxIdentificacion = new javax.swing.JTextField();
        jlbModificarUs = new javax.swing.JLabel();
        jlbContrasena2 = new javax.swing.JLabel();
        jlbRegistrarUs = new javax.swing.JLabel();
        jlbRegistrarUsuario = new javax.swing.JLabel();
        jlbMsjAdvertencia = new javax.swing.JLabel();
        jtxConsulta = new javax.swing.JTextField();
        btnConsulta = new javax.swing.JButton();
        cmbEstado = new javax.swing.JComboBox<>();
        cmbFuncionario = new javax.swing.JComboBox<>();
        cmbRol = new javax.swing.JComboBox<>();
        jlbFuncionario = new javax.swing.JLabel();
        jpsContrasena = new javax.swing.JPasswordField();
        jlbContrasena1 = new javax.swing.JLabel();
        jpsContrasena2 = new javax.swing.JPasswordField();
        jlbMsjAdvertencia2 = new javax.swing.JLabel();
        scrUsuarios = new javax.swing.JScrollPane();
        jtbTablaUsuarios = new javax.swing.JTable();
        jlbTitulo = new javax.swing.JLabel();
        jlbPrimero = new javax.swing.JLabel();
        jlbAtras = new javax.swing.JLabel();
        jlbSiguiente = new javax.swing.JLabel();
        jlbUltimo = new javax.swing.JLabel();
        cmbPaginacion = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jlbPaginas = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1400, 1000));

        jpnFondo.setBackground(new java.awt.Color(255, 255, 255));
        jpnFondo.setEnabled(false);
        jpnFondo.setPreferredSize(new java.awt.Dimension(5000, 1550));
        jpnFondo.setRequestFocusEnabled(false);
        jpnFondo.setVerifyInputWhenFocusTarget(false);
        jpnFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbRol.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jlbRol.setForeground(new java.awt.Color(51, 51, 51));
        jlbRol.setText("Rol");
        jpnFondo.add(jlbRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 490, 80, -1));

        jlbEstado.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jlbEstado.setForeground(new java.awt.Color(51, 51, 51));
        jlbEstado.setText("Estado");
        jpnFondo.add(jlbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 540, -1, -1));

        jlbModificarUsuario.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jlbModificarUsuario.setForeground(new java.awt.Color(51, 51, 51));
        jlbModificarUsuario.setText("Modificar ");
        jpnFondo.add(jlbModificarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 400, -1, -1));

        jlbUsuario.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jlbUsuario.setForeground(new java.awt.Color(51, 51, 51));
        jlbUsuario.setText("Usuario");
        jpnFondo.add(jlbUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 120, -1));

        jtxIdentificacion.setEditable(false);
        jtxIdentificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxIdentificacionActionPerformed(evt);
            }
        });
        jtxIdentificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxIdentificacionKeyTyped(evt);
            }
        });
        jpnFondo.add(jtxIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 210, -1));

        jlbModificarUs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/modificar1.png"))); // NOI18N
        jpnFondo.add(jlbModificarUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 380, -1, -1));

        jlbContrasena2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jlbContrasena2.setForeground(new java.awt.Color(51, 51, 51));
        jlbContrasena2.setText("Confirmación");
        jpnFondo.add(jlbContrasena2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 430, -1, -1));

        jlbRegistrarUs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/registrar1.png"))); // NOI18N
        jlbRegistrarUs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbRegistrarUs(evt);
            }
        });
        jpnFondo.add(jlbRegistrarUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 450, -1, -1));

        jlbRegistrarUsuario.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jlbRegistrarUsuario.setForeground(new java.awt.Color(51, 51, 51));
        jlbRegistrarUsuario.setText("Registrar ");
        jpnFondo.add(jlbRegistrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 470, -1, -1));

        jlbMsjAdvertencia.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jlbMsjAdvertencia.setForeground(new java.awt.Color(51, 51, 51));
        jlbMsjAdvertencia.setText("jLabel1");
        jpnFondo.add(jlbMsjAdvertencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 570, 540, -1));

        jtxConsulta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxConsultaKeyTyped(evt);
            }
        });
        jpnFondo.add(jtxConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 150, 30));

        btnConsulta.setBackground(new java.awt.Color(153, 0, 0));
        btnConsulta.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnConsulta.setForeground(new java.awt.Color(255, 255, 255));
        btnConsulta.setText("Consultar");
        jpnFondo.add(btnConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 100, 30));

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVO", "INACTIVO" }));
        jpnFondo.add(cmbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 540, 210, -1));

        jpnFondo.add(cmbFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 210, -1));

        cmbRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SECRETARIO", "INVITADO" }));
        cmbRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRolActionPerformed(evt);
            }
        });
        jpnFondo.add(cmbRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, 210, -1));

        jlbFuncionario.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jlbFuncionario.setForeground(new java.awt.Color(51, 51, 51));
        jlbFuncionario.setText("Funcionario");
        jpnFondo.add(jlbFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, -1, -1));

        jpsContrasena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpsContrasenaMouseClicked(evt);
            }
        });
        jpsContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpsContrasenaActionPerformed(evt);
            }
        });
        jpnFondo.add(jpsContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 390, 130, 20));

        jlbContrasena1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jlbContrasena1.setForeground(new java.awt.Color(51, 51, 51));
        jlbContrasena1.setText("Contraseña nueva ");
        jpnFondo.add(jlbContrasena1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, -1, -1));

        jpsContrasena2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpsContrasena2MouseClicked(evt);
            }
        });
        jpsContrasena2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpsContrasena2ActionPerformed(evt);
            }
        });
        jpnFondo.add(jpsContrasena2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 430, 130, 20));

        jlbMsjAdvertencia2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jlbMsjAdvertencia2.setForeground(new java.awt.Color(51, 51, 51));
        jlbMsjAdvertencia2.setText("jLabel1");
        jpnFondo.add(jlbMsjAdvertencia2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 540, -1));

        jtbTablaUsuarios.setBackground(new java.awt.Color(204, 204, 204));
        jtbTablaUsuarios.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jtbTablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificación", "Nombres", "Apellidos", "Telefono", "Correo", "Sede", ""
            }
        ));
        scrUsuarios.setViewportView(jtbTablaUsuarios);

        jpnFondo.add(scrUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 1210, 180));

        jlbTitulo.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jlbTitulo.setText("Usuarios");
        jpnFondo.add(jlbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, -1, -1));

        jlbPrimero.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jlbPrimero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ultimapagizq.png"))); // NOI18N
        jpnFondo.add(jlbPrimero, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 10, 15));

        jlbAtras.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jlbAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/izquierda.png"))); // NOI18N
        jpnFondo.add(jlbAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 10, 15));

        jlbSiguiente.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jlbSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/derecha.png"))); // NOI18N
        jlbSiguiente.setText("2");
        jpnFondo.add(jlbSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 10, 15));

        jlbUltimo.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jlbUltimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ultimapagder.png"))); // NOI18N
        jpnFondo.add(jlbUltimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 10, 15));

        cmbPaginacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "30", "50", "100" }));
        cmbPaginacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPaginacionActionPerformed(evt);
            }
        });
        jpnFondo.add(cmbPaginacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, -1, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel5.setText("Registros por página");
        jpnFondo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, 140, 20));

        jlbPaginas.setFont(new java.awt.Font("Verdana", 3, 11)); // NOI18N
        jlbPaginas.setText("Página 1 de 1000");
        jpnFondo.add(jlbPaginas, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, 120, 20));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1208, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 218, Short.MAX_VALUE)
        );

        jpnFondo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 1210, 220));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5020, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jpnFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 5020, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1550, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jpnFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jpsContrasena2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpsContrasena2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpsContrasena2ActionPerformed

    private void jpsContrasena2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpsContrasena2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jpsContrasena2MouseClicked

    private void jpsContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpsContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpsContrasenaActionPerformed

    private void jpsContrasenaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpsContrasenaMouseClicked

    }//GEN-LAST:event_jpsContrasenaMouseClicked

    private void cmbRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRolActionPerformed

    private void jlbRegistrarUs(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbRegistrarUs
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbRegistrarUs

    private void jtxIdentificacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxIdentificacionKeyTyped
        soloNumeros(evt);
    }//GEN-LAST:event_jtxIdentificacionKeyTyped

    private void jtxIdentificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxIdentificacionActionPerformed

    }//GEN-LAST:event_jtxIdentificacionActionPerformed

    private void jtxConsultaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxConsultaKeyTyped
        soloNumeros(evt);
    }//GEN-LAST:event_jtxConsultaKeyTyped

    private void cmbPaginacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPaginacionActionPerformed

    }//GEN-LAST:event_cmbPaginacionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnConsulta;
    public javax.swing.JComboBox<String> cmbEstado;
    public javax.swing.JComboBox<String> cmbFuncionario;
    public javax.swing.JComboBox<String> cmbPaginacion;
    public javax.swing.JComboBox<String> cmbRol;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel jlbAtras;
    public javax.swing.JLabel jlbContrasena1;
    public javax.swing.JLabel jlbContrasena2;
    public javax.swing.JLabel jlbEstado;
    public javax.swing.JLabel jlbFuncionario;
    public javax.swing.JLabel jlbModificarUs;
    private javax.swing.JLabel jlbModificarUsuario;
    public javax.swing.JLabel jlbMsjAdvertencia;
    public javax.swing.JLabel jlbMsjAdvertencia2;
    public javax.swing.JLabel jlbPaginas;
    public javax.swing.JLabel jlbPrimero;
    public javax.swing.JLabel jlbRegistrarUs;
    private javax.swing.JLabel jlbRegistrarUsuario;
    private javax.swing.JLabel jlbRol;
    public javax.swing.JLabel jlbSiguiente;
    private javax.swing.JLabel jlbTitulo;
    public javax.swing.JLabel jlbUltimo;
    public javax.swing.JLabel jlbUsuario;
    private javax.swing.JPanel jpnFondo;
    public javax.swing.JPasswordField jpsContrasena;
    public javax.swing.JPasswordField jpsContrasena2;
    public javax.swing.JTable jtbTablaUsuarios;
    public javax.swing.JTextField jtxConsulta;
    public javax.swing.JTextField jtxIdentificacion;
    private javax.swing.JScrollPane scrUsuarios;
    // End of variables declaration//GEN-END:variables
}
