
package Vista.Correspondencia;


public class ExternoModal extends javax.swing.JDialog {

    public ExternoModal(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jLabel3.setOpaque(true);
        jlbMsjAdvertencia2.setVisible(false);
        jlbMsjAdvertencia.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jtxConsulta = new javax.swing.JTextField();
        btnConsulta = new javax.swing.JButton();
        jlbMsjAdvertencia2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlbTipoDoc = new javax.swing.JLabel();
        jlbIdentificacion = new javax.swing.JLabel();
        jtxIdentificacion = new javax.swing.JTextField();
        cmbTipoDoc = new javax.swing.JComboBox<>();
        jlbNombres = new javax.swing.JLabel();
        jtxNombres = new javax.swing.JTextField();
        jlbApellidos = new javax.swing.JLabel();
        jtxApellidos = new javax.swing.JTextField();
        jtxtLugar = new javax.swing.JTextField();
        jlbLugar = new javax.swing.JLabel();
        jlbDireccion = new javax.swing.JLabel();
        jtxDireccion = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        scrFuncionarios = new javax.swing.JScrollPane();
        jtbTablaUsuarios = new javax.swing.JTable();
        jlbMsjAdvertencia = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(800, 550));
        jPanel4.setRequestFocusEnabled(false);
        jPanel4.setVerifyInputWhenFocusTarget(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxConsultaActionPerformed(evt);
            }
        });
        jtxConsulta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxConsultaKeyTyped(evt);
            }
        });
        jPanel4.add(jtxConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 130, 30));

        btnConsulta.setBackground(new java.awt.Color(153, 0, 0));
        btnConsulta.setForeground(new java.awt.Color(255, 255, 255));
        btnConsulta.setText("Consultar");
        jPanel4.add(btnConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 90, 30));

        jlbMsjAdvertencia2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jlbMsjAdvertencia2.setForeground(new java.awt.Color(51, 51, 51));
        jlbMsjAdvertencia2.setText("jLabel1");
        jPanel4.add(jlbMsjAdvertencia2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 540, -1));

        jLabel3.setBackground(new java.awt.Color(153, 0, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("                                                FUNCIONARIOS EXTERNOS");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 100));

        jlbTipoDoc.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jlbTipoDoc.setForeground(new java.awt.Color(51, 51, 51));
        jlbTipoDoc.setText("Tipo documento");
        jPanel4.add(jlbTipoDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, -1, -1));

        jlbIdentificacion.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jlbIdentificacion.setForeground(new java.awt.Color(51, 51, 51));
        jlbIdentificacion.setText("Identificación ");
        jPanel4.add(jlbIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 120, -1));

        jtxIdentificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxIdentificacionActionPerformed(evt);
            }
        });
        jtxIdentificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxIdentificacionKeyTyped(evt);
            }
        });
        jPanel4.add(jtxIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 170, -1));

        cmbTipoDoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TI", "CE", "CC" }));
        jPanel4.add(cmbTipoDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 170, -1));

        jlbNombres.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jlbNombres.setForeground(new java.awt.Color(51, 51, 51));
        jlbNombres.setText("Nombres");
        jPanel4.add(jlbNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, 80, -1));

        jtxNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxNombresActionPerformed(evt);
            }
        });
        jtxNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxNombresKeyTyped(evt);
            }
        });
        jPanel4.add(jtxNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, 170, -1));

        jlbApellidos.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jlbApellidos.setForeground(new java.awt.Color(51, 51, 51));
        jlbApellidos.setText("Apellidos ");
        jPanel4.add(jlbApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 510, -1, -1));

        jtxApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxApellidosKeyTyped(evt);
            }
        });
        jPanel4.add(jtxApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 510, 170, -1));
        jPanel4.add(jtxtLugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 550, 170, -1));

        jlbLugar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jlbLugar.setForeground(new java.awt.Color(51, 51, 51));
        jlbLugar.setText("Lugar");
        jPanel4.add(jlbLugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 550, 100, -1));

        jlbDireccion.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jlbDireccion.setForeground(new java.awt.Color(51, 51, 51));
        jlbDireccion.setText("Dirección");
        jPanel4.add(jlbDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, -1, -1));

        jtxDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxDireccionKeyTyped(evt);
            }
        });
        jPanel4.add(jtxDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 390, 210, -1));

        btnAceptar.setBackground(new java.awt.Color(153, 0, 0));
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setText("Registrar");
        jPanel4.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 560, 90, 30));

        jtbTablaUsuarios.setBackground(new java.awt.Color(204, 204, 204));
        jtbTablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificación", "Nombres", "Apellidos", "Lugar", "Dirección", ""
            }
        ));
        jtbTablaUsuarios.setRowSelectionAllowed(false);
        scrFuncionarios.setViewportView(jtbTablaUsuarios);

        jPanel4.add(scrFuncionarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 910, 180));

        jlbMsjAdvertencia.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jlbMsjAdvertencia.setForeground(new java.awt.Color(51, 51, 51));
        jlbMsjAdvertencia.setText("jLabel1");
        jPanel4.add(jlbMsjAdvertencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 590, 540, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 1020, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 631, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxConsultaActionPerformed

    private void jtxConsultaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxConsultaKeyTyped

    }//GEN-LAST:event_jtxConsultaKeyTyped

    private void jtxIdentificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxIdentificacionActionPerformed

    }//GEN-LAST:event_jtxIdentificacionActionPerformed

    private void jtxIdentificacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxIdentificacionKeyTyped
        soloNumeros(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_jtxIdentificacionKeyTyped

    private void jtxNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxNombresActionPerformed

    private void jtxNombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxNombresKeyTyped
        soloLetrasNombres(evt);
    }//GEN-LAST:event_jtxNombresKeyTyped

    private void jtxApellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxApellidosKeyTyped
        soloLetrasNombres(evt);  // TODO add your handling code here:
    }//GEN-LAST:event_jtxApellidosKeyTyped

    private void jtxDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxDireccionKeyTyped
    }//GEN-LAST:event_jtxDireccionKeyTyped

    public void soloNumeros(java.awt.event.KeyEvent evt) {
        char car = evt.getKeyChar();
        if (jtxDireccion.getText().length() >= 20 || jtxIdentificacion.getText().length() >= 20) {
            evt.consume();
        }
        if ((car < '0' || car > '9')) {
            evt.consume();
        }
    }

    public void soloLetras(java.awt.event.KeyEvent evt) {

        char car = evt.getKeyChar();
        System.out.println((int) car);
        if (jtxNombres.getText().length() >= 20 || jtxApellidos.getText().length() >= 20) {
            evt.consume();
        }
        if ((((int) car >= 65 && (int) car <= 90)) || (((int) car >= 97 && (int) car <= 122))) {

        } else {
            evt.consume();
        }

    }

    public void soloLetrasNombres(java.awt.event.KeyEvent evt) {

        char car = evt.getKeyChar();
        System.out.println((int) car);
        if (jtxNombres.getText().length() >= 20 || jtxApellidos.getText().length() >= 20) {
            evt.consume();
        }
        if ((((int) car >= 65 && (int) car <= 90)) || (((int) car >= 97 && (int) car <= 122)) || (int) car == 32) {

        } else {
            evt.consume();
        }

    }

 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExternoModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExternoModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExternoModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExternoModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ExternoModal dialog = new ExternoModal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAceptar;
    public javax.swing.JButton btnConsulta;
    public javax.swing.JComboBox<String> cmbTipoDoc;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel jlbApellidos;
    private javax.swing.JLabel jlbDireccion;
    public javax.swing.JLabel jlbIdentificacion;
    private javax.swing.JLabel jlbLugar;
    public javax.swing.JLabel jlbMsjAdvertencia;
    public javax.swing.JLabel jlbMsjAdvertencia2;
    private javax.swing.JLabel jlbNombres;
    public javax.swing.JLabel jlbTipoDoc;
    public javax.swing.JTable jtbTablaUsuarios;
    public javax.swing.JTextField jtxApellidos;
    public javax.swing.JTextField jtxConsulta;
    public javax.swing.JTextField jtxDireccion;
    public javax.swing.JTextField jtxIdentificacion;
    public javax.swing.JTextField jtxNombres;
    public javax.swing.JTextField jtxtLugar;
    private javax.swing.JScrollPane scrFuncionarios;
    // End of variables declaration//GEN-END:variables
}
